### ISSUE TITLE
Can you please add some license to this project?

### ISSUE THREAD

**Issue by ddmytrenko** [Acomodeo/kotlintest-spring#1]
Hi!

Thanks for the lib. I'm going to fork and extend it. But I have a problem with it just because you did not add any license here? Can you add it?

Thanks for an attention!

Best regards

**Comment by mhlz** [comment]
I just added a License to it.

Though I'd like to point out that we don't really use kotlintest internally anymore so I am not sure how well all of this works with current versions of Kotlin and Spring. 

If you want to fix bugs, feel free to make some Pull Requests though!

**Comment by ddmytrenko** [comment]
Thank you very much, Mischa! Yeah I'm going to support it ;)
