### ISSUE TITLE
Deploy to public repository (Maven-Central or JCenter)

### ISSUE THREAD

**Issue by bondpp7** [Acomodeo/kotlintest-spring#2]
Please deploy this to a public repository, such as maven-central (https://search.maven.org/) or JCenter (https://bintray.com/bintray/jcenter) so that it can be pulled in as a dependency via build tools such as Gradle or Maven.

**Comment by mhlz** [comment]
I included some documentation about downloading this project in the readme. You can just use https://jitpack.io to download a copy (this is also how we work internally with our libraries to minimize manual work).
